publishDir = "docs"
baseurl = "https://abelight.agilewarsaw.com"
title = "ABE Light 2024"
canonifyurls = true
theme = "hugo-conference"

[params]
Name = "ABE Light 2024"
Description = "AgileByExample Light 2024"
Date = "10 Marca (Niedziela)"
startDate = "2024-03-10T13:45"
Venue = "Akademia Leona KoÅºmiÅ„skiego"
Address = "ul. JagielloÅ„ska 57/59"
City = "Warsaw"
AddressRemarks = "Aulaâ€¦"
Images = [ "/img/ABElight-ikonka.png" ]
Sections = [
  "about",
  "location",
  "speakers",
  "schedule",
  "partners",
  "sponsors",
  "media",
  "orgs",
  "previous"
]


##########################
#   Link do rejestracji
##########################

[params.CallToAction]
text = "Zarejestruj siÄ™ (gratis)"
link = "register"


##########################
#   TytuÅ‚y sekcji 
##########################

[params.Titles]
about = "O konferencji"
location = "Gdzie?"
speakers = "Kto?"
schedule = "RozkÅ‚ad jazdy"
sponsors = "Sponsorzy"
partners = "Partnerzy"
media = "Partnerzy medialni"
orgs = "Organizatorzy"
contact = "Kontakt"
previous = "Poprzednie edycje"


####################################
#  Linki do poprzednich edycji
####################################

[[params.Previous]]
name = "2013"
url = "https://agilewarsaw.com/events/55/"

[[params.Previous]]
name = "2014"
url = "https://agilewarsaw.com/events/78/"

[[params.Previous]]
name = "2015"
url = "https://agilewarsaw.com/events/98/"

[[params.Previous]]
name = "2016"
url = "https://agilewarsaw.com/events/115/"

[[params.Previous]]
name = "2017"
url = "https://agilewarsaw.com/events/130/"

[[params.Previous]]
name = "2018"
url = "https://agilewarsaw.com/events/150/"

[[params.Previous]]
name = "2019"
url = "https://agilewarsaw.com/events/179/"

[[params.Previous]]
name = "2020"
url = "https://agilewarsaw.com/events/198/"

[[params.Previous]]
name = "2021"
url = "https://agilewarsaw.com/events/228/"

[[params.Previous]]
name = "2022"
url = "https://agilewarsaw.com/events/252/"

[[params.Previous]]
name = "2023"
url = "https://agilewarsaw.com/events/267/"


####################################
#  Sponsorzy
####################################

[[params.Sponsors]]
name = "DXC Technology"
logo = "img/logo-DXC.png"
url = "https://dxc.com/pl/en"

[[params.Sponsors]]
name = "ProCognita"
logo = "img/logo_procognita.png"
url = "https://procognita.pl/"

[[params.Sponsors]]
name = "Akademia Leona KoÅºmiÅ„skiego"
logo = "img/logo_ALK.png"
url = "https://www.kozminski.edu.pl/"

####################################
#  Partnerzy
####################################

[[params.Partners]]
name = "Agile Warsaw"
logo = "img/logo_AW.png"
url = "http://agilewarsaw.com"


[[params.Partners]]
name = "NextGen.PM"
logo = "img/logo_NextGenPM.png"
url = "https://nextgen.pm/"

####################################
#  Media
####################################

[[params.Media]]
name = "Agile Polska"
logo = "img/logo_APL.png"
url = "http://agilepolska.pl/"

# [[params.Media]]
# name = "Agile 247"
# logo = "img/logo_a247.jpg"
# url = "http://www.agile247.pl/"

# [[params.Media]]
# name = "Agile 4U"
# logo = "img/logo_agile4u.png"
# url = "https://www.meetup.com/agile4u/"

# [[params.Media]]
# name = "LubLean"
# logo = "img/logo_LubLean.png"
# url = "https://www.meetup.com/LubLean-and-Agile/"

# [[params.Media]]
# name = "Agile Silesia"
# logo = "img/logo_agile-silesia.png"
# url = "https://www.agilesilesia.pl/"

[[params.Media]]
name = "Kanban przy kawie"
logo = "img/logo_kanban_przy_kawie.png"
url = "https://kanbanprzykawie.pl/"

# [[params.Media]]
# name = "Agile WrocÅ‚aw"
# logo = "img/logo-agile-wroclaw.png"
# url = "https://www.meetup.com/pl-PL/agilewroclaw/"

# [[params.Media]]
# name = "ALE KrakÃ³w"
# logo = "img/logo-ale-krakow.png"
# url = "https://www.alekrakow.com/"

####################################
#  Organizatorzy
####################################

[[params.Orgs]]
name = "Ania Przybyszewska"
img = "img/org_przybyszewska_2.svg"

[[params.Orgs]]
name = "Ewelina Startek"
img = "img/org_startek_2.svg"

[[params.Orgs]]
name = "Ewa Koprowska"
img = "img/org_koprowska_2.svg"

[[params.Orgs]]
name = "Piotr Radaj"
img = "img/org_radaj_2.svg"

[[params.Orgs]]
name = "Åukasz SzÃ³stek"
img = "img/org_szostek_2.svg"

[[params.Orgs]]
name = "Katarzyna Prokopiuk"
img = "img/org_prokopiuk_2.svg"

[[params.Orgs]]
name = "Tomek SÅ‚owikowski"
img = "img/org_slowikowski_2.svg"


####################################
#  Rozpiska
####################################

#------------------------
#  Prelegenci
#------------------------

[[params.Schedule]]
name = "Zapisy na warsztaty"
time = "po poÅ‚udniu"
remark = 'Warto byÄ‡ na czas! Zapisy bÄ™dÄ… na miejscu i najciekawsze warsztaty zapeÅ‚niÄ… siÄ™ najszybciej.'

[[params.Schedule]]
name = "Otwarcie"
remark = 'TrochÄ™ informacji logistycznych i lecimy z programemâ€¦'


[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Tomasz Wykowski"
    photo = "img/TWykowski_2022.png"
    bio = "Od ponad dwÃ³ch dekad uczestniczÄ™ w tworzeniu produktÃ³w software'owych, a od ponad piÄ™tnastu lat dzielÄ™ siÄ™ swojÄ… wiedzÄ… poprzez szkolenia i konsulting. Jestem jedynym polskim Certified Scrum Trainer, CST akredytowanym przez Scrum Alliance oraz jednym z dwÃ³ch polskich Certified LeSS Coach. W przerwach pomiÄ™dzy pracÄ… z liderami rÃ³Å¼nych firm piszÄ™ artykuÅ‚y i nagrywam podcasty, ktÃ³re znajdziesz na stronie ProCognity. Jestem autorem ksiÄ…Å¼ki \"Biznes Odczarowany. Scrum: jak osiÄ…gaÄ‡ cele, gdy wszystko siÄ™ zmienia?\", w ktÃ³rej opowiadam jak uniknÄ…Ä‡ iluzji nierealnych planÃ³w i stworzyÄ‡ zwinnÄ… firmÄ™."

      [params.Schedule.authors.link]
        href = "https://www.linkedin.com/in/wykowski/"
        text = "LinkedIn"

    [params.Schedule.presentation]
      title = 'TBD'
      description ='TBD'
#------------------------

[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Kuba Szczepanik"
    photo = "img/szczepanik.jpg"
    bio = """
    Pomagam przejÅ›Ä‡ przez zmianÄ™ firmom, ktÃ³re chcÄ… wykorzystaÄ‡ potencjaÅ‚ tkwiÄ…cy w zwinnoÅ›ci.<br>
     Jestem konsultantem, mentorem i trenerem, specjalizujÄ…cym siÄ™ w temacie zwinnych transformacji duÅ¼ych organizacji. Wspieram bezpoÅ›rednio zespoÅ‚y projektowe rozwijajÄ…ce swoje produkty i pomagam wyjÅ›Ä‡ z podejÅ›ciem zwinnym do krÄ™gÃ³w â€biznesowychâ€ w firmach. <br>
     MojÄ… misjÄ… jest propagowanie porzÄ…dnej zwinnoÅ›ci w zespoÅ‚ach i firmach oraz przeciwstawienie siÄ™ pÅ‚ytkim zmianom oraz stosowania Agile-In-The-Name-Only. <br>
     Jestem wspÃ³Å‚autorem portalu <a href="https://agile247.pl">agile247.pl</a> i podcastu â€PorzÄ…dny Agileâ€, piszÄ™ teÅ¼ na swoim blogu kubaszczepanik.pl i szykujÄ™ ksiÄ…Å¼kÄ™ o zwinnych transformacjach â€“ wiÄ™cej informacji na stronie <a href="https://zwinneorganizacje.pl">zwinneorganizacje.pl</a>.
    """

    [params.Schedule.authors.link]
      href = "https://www.kubaszczepanik.pl/"
      text = "kubaszczepanik.pl"

    [params.Schedule.presentation]
      title = 'Jak Scrum Master moÅ¼e wesprzeÄ‡ efektywnoÅ›Ä‡ zespoÅ‚u?'
      description ="""
      EfektywnoÅ›Ä‡ zespoÅ‚Ã³w to temat bardzo istotny biznesowo i jednoczeÅ›nie traktowany doÅ›Ä‡ po macoszemu w wielu firmach. Nie jest to Å‚atwe â€“ rodzi pytania jak jÄ… mierzyÄ‡, kto ma na niÄ… wpÅ‚yw i jak jÄ… poprawiÄ‡. <br>
      Na bazie doÅ›wiadczeÅ„ w pracy z organizacjami przedstawiÄ™ moja propozycjÄ™ planu dziaÅ‚ania dla Scrum Mastera, ktÃ³ry chce przejÄ…Ä‡ inicjatywÄ™ i uruchomiÄ‡ dziaÅ‚ania zwiÄ…zane z podwyÅ¼szeniem efektywnoÅ›ci. PokaÅ¼Ä™ teÅ¼ model do auto-refleksji dla Scrum Mastera â€“ jakie kompetencje sÄ… potrzebne, Å¼eby realnie wpÅ‚ynÄ…Ä‡ na omawiany temat.
      """
#------------------------

[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Agnieszka CieÅ›lawska"
    photo = ""
    bio = ""

      # [params.Schedule.authors.link]
      #   href = ""
      #   text = ""

    [params.Schedule.presentation]
      title = 'TBD'
      description ='TBD'

####################################
# Warsztaty
####################################

#-----------------------------------------------------------
# Opis warsztatÃ³w w tabelce, dane warsztatodawcÃ³w sÄ… niÅ¼ej
#-----------------------------------------------------------

[[params.Schedule]]
name = "Warsztaty"
remark = """

Wszystkie warsztaty bÄ™dÄ… siÄ™ toczyÅ‚y jednoczeÅ›nie / rÃ³wnolegle czyli moÅ¼esz doÅ‚Ä…czyÄ‡ tylko do jednego z nich.

Zapisy odbÄ™dÄ… siÄ™ na miejscu, przed otwarciem konferencji. SpÃ³jrz ğŸ‘†ğŸ‘†

<br><br>

<strong>Ewa Koprowska</strong><br>
TBD
<br><br>


<strong>Joanna PÅ‚askonka</strong><br>
TBD


<br><br>

<strong>Agata Kabat</strong><br>
TBD


<br><br>

<strong>Tomek Serafin i Jakub Dobosz<br>
Symulacja Scruma: obraz czy 1000 sÅ‚Ã³w?
</strong><br>

Z przewodnika po Scrumie: Scrum to "uproszczone ramy postÄ™powania, ktÃ³re pomagajÄ… [â€¦] wytwarzaÄ‡ wartoÅ›Ä‡ poprzez adaptacyjne rozwiÄ…zywanie zÅ‚oÅ¼onych problemÃ³w". <br>
Czy przewodnik po Scrumie jest tak prosty jak to moÅ¼liwe? Jak dobrze rozumiemy podstawowe elementy metody i do jakiego stopnia nasze rozumienie jest zgodne z rozumieniem innych? Czy potrafimy wyjaÅ›niÄ‡ Scruma innym nie uÅ¼ywajÄ…c trudnych sÅ‚Ã³w? <br>
Na te i inne pytania odpowiemy sobie w trakcie warsztatu, w trakcie ktÃ³rego bÄ™dziemy wytwarzaÄ‡ wartoÅ›Ä‡ (zrozumienie Scruma) przez adaptacyjne rozwiÄ…zywanie zÅ‚oÅ¼onego problemu (jak to zrobiÄ‡ dobrze?) - wyjaÅ›nijmy Scruma pracujÄ…c Scrumem!


<br><br>

<strong>Adrian Janik i Mateusz Hauk</strong><br>
TBD


<br><br>

<strong>Tomek Wykowski</strong><br>
TBD


<br><br>

<strong>Krzysztof NiewiÅ„ski</strong><br>
TBD


<br><br>

<strong>Justyna Wykowska i Karolina</strong><br>
TBD


<br><br>

<strong>Magda GaÅ‚aj i Marcin GaÅ‚aj</strong><br>
TBD

"""

#########################
# Impreza 
#########################

[[params.Schedule]]
  name = "Afterparty!"
  time = "~19:00"


#---------------------------------------
# Warsztatodawcy -- tylko wizytÃ³wki! 
# tematy warsztatÃ³w sÄ… w rozpisce powyÅ¼ej
#---------------------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Ewa Koprowska"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Joanna PÅ‚askonka"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Agata Kabat"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Tomek Serafin"
  photo = "img/serafin.jpg"
  bio = """
ZaczynaÅ‚em karierÄ™ zawodowÄ… jako programista, nastÄ™pnie tworzyÅ‚em i dostarczaÅ‚em wartoÅ›Ä‡ jako analityk, menadÅ¼er projektu, menadÅ¼er produktu, lider zespoÅ‚u, Scrum Master, a nawet Head of HR. <br>
Obecnie jestem programistÄ… i przywÃ³dcÄ… sÅ‚uÅ¼ebnym zespoÅ‚u Scrumowego. Jednym z moich hobby jest tworzenie oraz prowadzenie warsztatÃ³w wzmacniajÄ…cych zrozumienie zwinnoÅ›ci. LubiÄ™ zrozumienie.
  """
  [params.Schedule.authors.link]
    href = 'https://www.linkedin.com/in/tpserafin/'
    text = "LinkedIn"

  [[params.Schedule.authors]]
  name = "Jakub Dobosz"
  photo = "img/dobosz.jpg"
  bio = """
CeniÄ™ synergiÄ™ zespoÅ‚u, przejrzystoÅ›Ä‡ i skutecznÄ… komunikacjÄ™. Skupiam siÄ™ na wartoÅ›ci biznesowej i szukaniu sposobÃ³w na jej optymalne dostarczanie. WierzÄ™, Å¼e poprzez ciÄ…gÅ‚e zwiÄ™kszanie naszego zrozumienia wÅ‚asnych potrzeb i motywacji jesteÅ›my w stanie tworzyÄ‡ wyjÄ…tkowe rozwiÄ…zania. Jednym z moich celÃ³w jest budowanie Å›rodowisk, gdzie kaÅ¼dy ma poczucie wÅ‚asnoÅ›ci i moÅ¼liwoÅ›Ä‡ wpÅ‚ywania na nie. PraktykujÄ™ NVC i zwiÄ™kszanie swojej uwaÅ¼noÅ›ci.
  """
   [params.Schedule.authors.link]
    href = 'https://www.linkedin.com/in/jakubdobosz/'
    text = "LinkedIn"

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Adrian Janik"
  photo = "img/janik.jpg"
  bio = """
  Od 15 lat zajmujÄ™ siÄ™ szkoleniem, rozwijaniem kompetencji miÄ™kkich. Od 5 lat odkrywam Å›wiat zwinnych zespoÅ‚Ã³w i przynoszÄ™ do niego narzÄ™dzia i rozwiÄ…zania wzmacniajÄ…ce zespoÅ‚owoÅ›Ä‡, samoorganizacjÄ™ oraz wspÃ³Å‚odpowiedzialnoÅ›Ä‡.  Wspieram organizacje w planowaniu i skutecznym wdraÅ¼aniu zmian, dostarczam wiedzÄ™ i umiejÄ™tnoÅ›ci zwiÄ…zane z kompetencjami osobistymi, komunikacjÄ… oraz zespoÅ‚owoÅ›ciÄ…. Pomagam liderom i czÅ‚onkom zespoÅ‚Ã³w skutecznie peÅ‚niÄ‡ ich role, a przez to budowaÄ‡ samodzielne i odpowiedzialne teamy. <br>
  Jako trener i psycholog gÅ‚Ä™boko wierzÄ™, Å¼e dobre relacje sÄ… nie tylko kluczem do sukcesu zespoÅ‚Ã³w i organizacji, ale teÅ¼ ÅºrÃ³dÅ‚em dobrego i peÅ‚nego Å¼ycia. <br>
  Prywatnie podrÃ³Å¼ujÄ™ i biegam, a pÃ³Åºniej odpoczywam z ksiÄ…Å¼kÄ… w rÄ™ku.
  """
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

  [[params.Schedule.authors]]
  name = "Mateusz Hauk"
  photo = "img/hauk.jpg"
  bio = """
  Trener biznesu od 2005 roku. Certyfikowany Scrum Master.  <br>
  W dziaÅ‚aniach rozwojowych propaguje ideÄ™ â€ZarzÄ…dzania z ludzkÄ… twarzÄ…â€. Wspiera zespoÅ‚y samoorganizujÄ…ce (agile). WspÃ³Å‚autor wielu dedykowanych programÃ³w rozwojowych dla liderÃ³w i menedÅ¼erÃ³w, koordynator metodologiczny i trener wiodÄ…cy akademii menedÅ¼erskich. WspÃ³Å‚autor koncepcji i koordynator merytoryczny projektÃ³w zwiÄ…zanych z tworzeniem platform e-learningowych i e-coachingowych <br>
  Realizuje szkolenia z zakresu: <br>
  â€¢ UmiejÄ™tnoÅ›ci szefowskich i menedÅ¼erskich <br>
  â€¢ Komunikacji i asertywnoÅ›ci <br>
  â€¢ Budowania i usprawniania pracy zespoÅ‚Ã³w <br>
  â€¢ Facylitacji i moderacji <br>
  â€¢ Budowania i usprawniania relacji w miejscu pracy <br>
  â€¢ SkutecznoÅ›ci osobistej (kapitaÅ‚ psychologiczny i spoÅ‚eczny) <br>
  â€¢ WdraÅ¼ania i wzmacniania zmian <br>
  â€¢ Wykorzystywania agile w biznesie """
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Krzysztof NiewiÅ„ski"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    #   href = ""
    #   text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Justyna Wykowska"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

  # [[params.Schedule.authors]]
  # name = "Karolina"
  # photo = ""
  # bio = ""
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

#------------------------

[[params.Schedule]]
workshop = true

  [[params.Schedule.authors]]
  name = "Magda GaÅ‚aj"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

  [[params.Schedule.authors]]
  name = "Marcin GaÅ‚aj"
  photo = ""
  bio = ""
    # [params.Schedule.authors.link]
    # href = ""
    # text = ""

#------------------------