publishDir = "docs"
baseurl = 'https://abelight.agilewarsaw.com'
title = "ABE Light 2025"
canonifyurls = true
theme = "hugo-conference"

[params]
Name = "ABE Light 2025"
Description = "AgileByExample Light 2025"
Date = "6 Kwietnia (Niedziela)"
startDate = "2025-04-06T13:45"
Venue = "Akademia Leona KoÅºmiÅ„skiego"
Address = "ul. JagielloÅ„ska 57/59"
City = "Warsaw"
AddressRemarks = "Aulaâ€¦"
Images = [ "/img/ABElight-ikonka.png" ]
Sections = [
  "about",
  "location",
  "speakers",
  "schedule",
  "partners",
  "sponsors",
  "media",
  "orgs",
  "previous"
]


##########################
#   Link do rejestracji
##########################

[params.CallToAction]
text = "Zarejestruj siÄ™ (gratis)"
link = "register"


##########################
#   TytuÅ‚y sekcji 
##########################

[params.Titles]
about = "O konferencji"
location = "Gdzie?"
speakers = "Kto?"
schedule = "RozkÅ‚ad jazdy"
sponsors = "Sponsorzy"
partners = "Partnerzy"
media = "Partnerzy medialni"
orgs = "Organizatorzy"
contact = "Kontakt"
previous = "Poprzednie edycje"


####################################
#  Linki do poprzednich edycji
####################################

[[params.Previous]]
name = "2013"
url = 'https://agilewarsaw.com/events/55/'

[[params.Previous]]
name = "2014"
url = 'https://agilewarsaw.com/events/78/'

[[params.Previous]]
name = "2015"
url = 'https://agilewarsaw.com/events/98/'

[[params.Previous]]
name = "2016"
url = 'https://agilewarsaw.com/events/115/'

[[params.Previous]]
name = "2017"
url = 'https://agilewarsaw.com/events/130/'

[[params.Previous]]
name = "2018"
url = 'https://agilewarsaw.com/events/150/'

[[params.Previous]]
name = "2019"
url = 'https://agilewarsaw.com/events/179/'

[[params.Previous]]
name = "2020"
url = 'https://agilewarsaw.com/events/198/'

[[params.Previous]]
name = "2021"
url = 'https://agilewarsaw.com/events/228/'

[[params.Previous]]
name = "2022"
url = 'https://agilewarsaw.com/events/252/'

[[params.Previous]]
name = "2023"
url = 'https://agilewarsaw.com/events/267/'

[[params.Previous]]
name = "2024"
url = 'https://agilewarsaw.com/events/292/'


####################################
#  Sponsorzy
####################################

[[params.Sponsors]]
name = "Akademia Leona KoÅºmiÅ„skiego"
logo = "img/logo_ALK.png"
url = 'https://www.kozminski.edu.pl/'


[[params.Sponsors]]
name = "BEC Poland"
logo = "img/logo_bec.png"
url = 'https://www.linkedin.com/company/becpoland/'

####################################
#  Partnerzy
####################################

[[params.Partners]]
name = "Agile Warsaw"
logo = "img/logo_AW.png"
url = "http://agilewarsaw.com"


[[params.Partners]]
name = "NextGen.PM"
logo = "img/logo_NextGenPM.png"
url = 'https://nextgen.pm/'

####################################
#  Media
####################################

# [[params.Media]]
# name = "Agile Polska"
# logo = "img/logo_APL.png"
# url = "http://agilepolska.pl/"

[[params.Media]]
name = "Kanban przy kawie"
logo = "img/logo_kanban_przy_kawie.png"
url = 'https://kanbanprzykawie.pl/'

# [[params.Media]]
# name = "Agile 247"
# logo = "img/logo_a247.jpg"
# url = "http://www.agile247.pl/"

# [[params.Media]]
# name = "Agile 4U"
# logo = "img/logo_agile4u.png"
# url = 'https://www.meetup.com/agile4u/'

# [[params.Media]]
# name = "LubLean"
# logo = "img/logo_LubLean.png"
# url = 'https://www.meetup.com/LubLean-and-Agile/'

# [[params.Media]]
# name = "Agile WrocÅ‚aw"
# logo = "img/logo-agile-wroclaw.png"
# url = 'https://www.meetup.com/pl-PL/agilewroclaw/'

# [[params.Media]]
# name = "Agile PoznaÅ„"
# logo = "img/logo_agile_poznan.png"
# url = 'https://www.linkedin.com/groups/4406793'

[[params.Media]]
name = "Agile 3M"
logo = "img/logo_agile3m.png"
url = 'https://www.linkedin.com/company/agile3m'

# [params.Media]]
# ame = "Agile Silesia"
# ogo = "img/logo_agile-silesia.png"
# rl = 'https://www.agilesilesia.pl/'

# [params.Media]]
# ame = "ALE KrakÃ³w"
# ogo = "img/logo-ale-krakow.png"
# rl = 'https://www.alekrakow.com/'

# [params.Media]]
# ame = "Dare IT"
# ogo = 'img/logo_DareIT.png'
# rl = 'https://www.dareit.io/'

# [params.Media]]
# ame = "Zwinna ÅÃ³dÅº"
# ogo = 'img/logo_zwinna_lodz.svg'
# rl = 'https://www.meetup.com/Zwinna-Lodz/'

####################################
#  Organizatorzy
####################################

[[params.Orgs]]
name = "Ania Przybyszewska"
img = "img/org_przybyszewska_2.svg"

[[params.Orgs]]
name = "Ewelina Startek"
img = "img/org_startek_2.svg"

# [params.Orgs]]
# ame = "Ewa Koprowska"
# mg = "img/org_koprowska_2.svg"

[[params.Orgs]]
name = "Piotr Radaj"
img = "img/org_radaj_2.svg"

# [params.Orgs]]
# ame = "Katarzyna Prokopiuk"
# mg = "img/org_prokopiuk_2.svg"

[[params.Orgs]]
name = "Tomek SÅ‚owikowski"
img = "img/org_slowikowski_2.svg"

[[params.Orgs]]
name = "Åukasz SzÃ³stek"
img = "img/org_szostek_2.svg"


####################################
#  Rozpiska
####################################

#------------------------
#  Prelegenci
#------------------------

[[params.Schedule]]
name = "Zapisy na warsztaty"
time = "XX:XX"
remark = 'Warto byÄ‡ na czas! Zapisy bÄ™dÄ… na miejscu i najciekawsze warsztaty zapeÅ‚niÄ… siÄ™ najszybciej.'

[[params.Schedule]]
name = "Otwarcie konferencji"
time = "XX:XX"
remark = 'TrochÄ™ informacji logistycznych i lecimy z programemâ€¦'

#------------------------

[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Aga SzÃ³stek"
    photo = ""
    bio = "Dr Aga SzÃ³stek jest autorkÄ… "Strategii Umami" oraz "ZostaÅ„ liderem, jakim chcesz!" i ekspertkÄ… w zakresie strategii i przywÃ³dztwa.

Przez ostatnie dwie dekady wspÃ³Å‚pracowaÅ‚a z czoÅ‚Ã³wkÄ… firm Å‚Ä…czÄ…cych design, technologiÄ™ i biznes. PracowaÅ‚a z takimi markami jak Google, Philips, Samsung, Play, Allegro, EY, Santander, ING, Orange i wieloma innymi, wnoszÄ…c do zespoÅ‚Ã³w projektowych i zarzÄ…dÃ³w strategiczne podejÅ›cie oparte na projektowaniu doÅ›wiadczeÅ„.

Aga wspiera takÅ¼e swoich klientÃ³w w rozwoju liderskim w oparciu o kluczowe wyzwania przywÃ³dcze zakotwiczone w ich organizacyjnej kulturze. Oferuje unikatowe programy liderskie dostarczane w formie niezapomnianego doÅ›wiadczenia."

      [params.Schedule.authors.link]
        href = ''
        text = ''

    [params.Schedule.presentation]
      title = 'TytuÅ‚ TBD'
      description = """ Opis TBD """

#------------------------

[[params.Schedule]]
    [[params.Schedule.authors]]
    name = "Kate Hobler"
    photo = ""
    bio = ""

      [params.Schedule.authors.link]
        href = ''
        text = ''

    [params.Schedule.presentation]
      title = 'TytuÅ‚ TBD'
      description = """ Opis TBD """

#------------------------

####################################
# Warsztaty
####################################

#-----------------------------------------------------------
# Opis warsztatÃ³w w tabelce, dane warsztatodawcÃ³w sÄ… niÅ¼ej
#-----------------------------------------------------------

[[params.Schedule]]
name = "Warsztaty"
remark = """

 Wszystkie warsztaty bÄ™dÄ… siÄ™ toczyÅ‚y jednoczeÅ›nie / rÃ³wnolegle czyli moÅ¼esz doÅ‚Ä…czyÄ‡ tylko do jednego z nich.

Zapisy odbÄ™dÄ… siÄ™ na miejscu, przed otwarciem konferencji. SpÃ³jrz ğŸ‘†ğŸ‘†

<br><br>

<strong>Justyna (KÄ™sik) RÄ™dzikowska
<br> 
Lider(ka) w Åšwiecie Liczb: Jak KomunikowaÄ‡ Metryki, by BudowaÄ‡ ZaangaÅ¼owanie
<br>
</strong>
<br>
Czy chcesz lepiej pracowaÄ‡ z metrykami i zaangaÅ¼owaÄ‡ w to caÅ‚y zespÃ³Å‚? Czy chcesz opieraÄ‡ swojÄ… pracÄ™ na danych i wnieÅ›Ä‡ znaczÄ…cy wkÅ‚ad w retrospektywy? Wiesz, jak waÅ¼ne sÄ… metryki, ale zawsze trudno byÅ‚o Ci je efektywnie komunikowaÄ‡ z zespoÅ‚em?
<br>
Ten warsztat jest idealny dla Ciebie! :)
<br><br>
Zaczniemy od okreÅ›lenia celu i miejsca naszych dziaÅ‚aÅ„ w Å¼yciu zespoÅ‚u. OmÃ³wimy podstawowe metryki procesowe oraz jak o nich rozmawiaÄ‡ z zespoÅ‚em w sposÃ³b, ktÃ³ry buduje zaangaÅ¼owanie i poczucie bezpieczeÅ„stwa.
 
<br><br>
Podczas warsztatu dowiesz siÄ™:
<ul style=\"padding-left: 0.5em;\">
<li>â€¢ Jak efektywnie komunikowaÄ‡ metryki, aby zespÃ³Å‚ czuÅ‚ siÄ™ zaangaÅ¼owany i bezpieczny.</li>
<li>â€¢ Jak angaÅ¼owaÄ‡ zespÃ³Å‚ w pracÄ™ z danymi, aby wspÃ³lnie dÄ…Å¼yÄ‡ do wzrostu, a nie oceniaÄ‡ ludzi.</li>
<li>â€¢ Jak tworzyÄ‡ kulturÄ™ zaufania i otwartoÅ›ci wokÃ³Å‚ metryk</li>
</ul>
<br>
ZakoÅ„czymy warsztat analizÄ… rzeczywistych przypadkÃ³w, najpierw z moich zespoÅ‚Ã³w, a nastÄ™pnie z Twoich, abyÅ› mÃ³gÅ‚ wyjÅ›Ä‡ z gotowymi pomysÅ‚ami do wdroÅ¼enia juÅ¼ nastÄ™pnego dnia.


<br><br>

<strong> Staszek Matczak <br> 
 Jira dla dorosÅ‚ych - czyli o tym jak moÅ¼na skopaÄ‡ wizualizacjÄ™ pracy i o tym jak moÅ¼na jÄ… naprawiÄ‡
 <br>
</strong>
<br>
Mamy interesujÄ…cÄ… sytuacjÄ™. Z jednej strony jednym z filarÃ³w Scruma jest przejrzystoÅ›Ä‡: ,,praca musi byÄ‡ widoczna dla osÃ³b jÄ… wykonujÄ…cych, jak rÃ³wnieÅ¼ dla osÃ³b, na rzecz ktÃ³rych praca ta jest wykonywana''. A z drugiej strony narzÄ™dzia, ktÃ³re sÅ‚uÅ¼Ä… do wizualizacji pracy - takie jak na przykÅ‚ad Jira - sÄ… bardzo czÄ™sto przedmiotem Å¼artÃ³w, memÃ³w i heheszkÃ³w.
<br><br>
Podczas warsztatu sprÃ³bujemy znaleÅºÄ‡ odpowiedzi na pytania:
<ul style=\"padding-left: 0.5em;\">
<li>â€¢ Po co w ogÃ³le stosujemy narzÄ™dzia do planowania i monitorowania pracy? </li>
<li>â€¢ Jakie sÄ… potrzeby osÃ³b ktÃ³re wprowadzajÄ… narzÄ™dzia oraz osÃ³b, ktÃ³re sÄ… uÅ¼ytkownikami tych narzÄ™dzi? </li>
<li>â€¢ Czy moÅ¼emy pogodziÄ‡ potrzeby rÃ³Å¼nych interesariuszy? </li>
<li>â€¢ Co moÅ¼e kryÄ‡ siÄ™ pod niechÄ™ciÄ… do uÅ¼ywania narzÄ™dzi? </li>
<li>â€¢ I czy Jira Admin to nowy Agile Coach?</li>
<br>
Zapraszam osoby, ktÃ³re chcÄ… przyjrzeÄ‡ siÄ™ nie tylko warstwie narzÄ™dzi i procesÃ³w, ale chcÄ… spojrzeÄ‡ gÅ‚Ä™biej - na osoby, interakcje, potrzeby oraz strategie realizacji tych potrzeb. SprawdÅºmy co moÅ¼na zrobiÄ‡, Å¼eby narzÄ™dzia nam pomagaÅ‚y a nie utrudniaÅ‚y pracÄ™!
<br><br>
Dla peÅ‚nej jasnoÅ›ci: nie jestem sponsorowany przez Atlassiana i nie jest to prezentacja sprzedaÅ¼owa. A po drugie: sÅ‚owo ,,Jira'' w tytule moÅ¼e byÄ‡ zastÄ…pione przez dowolne inne narzÄ™dzie do planowania i zarzÄ…dzania pracÄ….



<br><br>


<strong> Trener <br> 
 TytuÅ‚ warsztatu 
 <br>
</strong>
 Opis warsztatu 2<br>
 cd...
 
"""

#########################
# Impreza 
#########################

[[params.Schedule]]
  name = "Afterparty!"
  time = "~XX:XX"


#---------------------------------------
# Warsztatodawcy -- tylko wizytÃ³wki! 
# tematy warsztatÃ³w sÄ… w rozpisce powyÅ¼ej
#---------------------------------------

[[params.Schedule]]
workshop = true

  # multiple authors per workshop are OK
  [[params.Schedule.authors]]
  name = "Justyna (KÄ™sik) RÄ™dzikowska"
  photo = "img/redzikowska.png"
  bio = """
  SpecjalizujÄ™ siÄ™ w Ways of Working. BudujÄ™ efektywne zespoÅ‚y, wspierajÄ…ce spoÅ‚ecznoÅ›ci, wbijam level up organizacjom. PracujÄ™ z wartoÅ›ciami, ludÅºmi, danymi i procesami. Uwielbiam siÄ™ uczyÄ‡ oraz dzieliÄ‡ wiedzÄ…. 
  <br>
  Od 2003 rozwijam siÄ™ jako liderka, a od 2006 jako trenerka, facylitatorka i mentorka.
  <br>
  LubiÄ™ zadawaÄ‡ pytania, ogromnie ciekawi mnie Å›wiat, czÅ‚owiek i procesy jakie zachodzÄ… pomiÄ™dzy.
  <br>
  Aktualnie dziaÅ‚am jako Scrum/Kanban Masterka oraz Agile Coachka w Danonie, choÄ‡ na umowie mi napisano, Å¼e jestem Starszym Kierownikiem, a ja ani stara ani panowie pod Å»abkÄ… nie mÃ³wiÄ… mi "Kierowniczko" ;)
  """
    [params.Schedule.authors.link]
      text = 'LinkedIn'
      href = 'https://www.linkedin.com/in/justyna-redzikowska/'


[[params.Schedule]]
workshop = true

  # multiple authors per workshop are OK
  [[params.Schedule.authors]]
  name = "Staszek Matczak"
  photo = "img/matczak.jpg"
  bio = """
  Po studiach niespodziewanie okazaÅ‚o siÄ™, Å¼e trzeba zarabiaÄ‡ na Å¼ycie â€“ wiÄ™c poszedÅ‚em do pracy.
ZaczynaÅ‚em od pisania kodu. PoniewaÅ¼ w miarÄ™ dobrze dogadywaÅ‚em siÄ™ z ludÅºmi, zaproponowano
mi stanowisko kierownika zespoÅ‚u. PlanowaÅ‚em prace, rozdzielaÅ‚em zadania, rozwiÄ…zywaÅ‚em
problemy, rozmawiaÅ‚em z ludÅºmiâ€¦ Jednak coraz bardziej czuÅ‚em, Å¼e w naszym IT coÅ› nie gra.
PracowaliÅ›my wspÃ³lnie z utalentowanymi, zaangaÅ¼owanymi ludÅºmi, a mimo to ciÄ…gle pojawiaÅ‚y siÄ™
opÃ³Åºnienia, wtopy i poraÅ¼ki.<br> 
SzukajÄ…c lepszych sposobÃ³w pracy odkryÅ‚em najpierw Scruma, a potem kolejne metody i koncepcje
zwinne â€“ Kanbana, zbiÃ³r metod z M3.0, sposoby skalowaniaâ€¦ WciÄ…gnÄ™Å‚o mnie to bardzo. Przez jakiÅ›
czas Å‚Ä…czyÅ‚em rolÄ™ menedÅ¼era zespoÅ‚u i Scrum Mastera, potem menedÅ¼era zespoÅ‚u i Product Ownera,
aÅ¼ wreszcie porzuciÅ‚em zarzÄ…dzanie i skupiÅ‚em siÄ™ na wdraÅ¼aniu metod zwinnych.
Czego siÄ™ nauczyÅ‚em? Å»e metody zwinne sÄ… proste do zrozumienia, ale trudne do zastosowania. Å»e
organizacje brawurowo walczÄ… z problemami, ktÃ³re same sobie stwarzajÄ…. Å»e warto jest
niestrudzenie zadawaÄ‡ pytanie â€dlaczego?â€. Å»e czÄ™sto chÄ™Ä‡ zmiany jest powierzchowna. Å»e nie
zawsze Scrum jest dobrym rozwiÄ…zaniem problemu. Å»e wszystko opiera siÄ™ na wartoÅ›ciach.
Jestem ojcem trÃ³jki wspaniaÅ‚ych dzieci, wspÃ³Å‚organizatorem trÃ³jmiejskiej spoÅ‚ecznoÅ›ci Agile3M.
KiedyÅ› pisaÅ‚em coÅ› na blogu www.trzeciakawa.pl 
  """
    [params.Schedule.authors.link]
      text = 'LinkedIn'
      href = 'https://www.linkedin.com/in/staszekmatczak/'



#[[params.Schedule]]
#workshop = true
#
  ## multiple authors per workshop are OK
  #[[params.Schedule.authors]]
  #name = ""
  #photo = ""
  #bio = """
  #"""
    #[params.Schedule.authors.link]
      #text = ''
      #href = ''
#------------------------
