publishDir: docs
baseurl: "https://abelight.agilewarsaw.com"
title: "ABE Light 2023"
canonifyurls: true
theme: "hugo-conference"

#GoogleAnalytics: "UA-112461830-1"

params:
  # Conference info
  Name: "ABE Light 2023"
  Description: "AgileByExample Light 2023"
  Date: "18 March (Saturday)"
  startDate: "2023-03-18T13:45"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "BEC Poland"
  Address: "Emilii Plater 53"
  City:  "Warsaw"
  AddressRemarks: "(floor 23, take the 'A' lifts)"
  #State: "Quintana"
  Images: ["/img/ABElight-ikonka.png"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - partners
    - sponsors
    - media
    - orgs
    - previous
      #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About the conference"
    location: "Where?"
    speakers: "Who?"
    schedule: "Timetable"
    sponsors: "Sponsors"
    partners: "Partners"
    media: "Media Partners"
    orgs: "Organizers"
    contact: "Contact"
    previous: "Previous Editions"

  Previous:
    - name: "2013"
      url: "https://agilewarsaw.com/events/55/"
    - name: "2014"
      url: "https://agilewarsaw.com/events/78/"
    - name: "2015"
      url: "https://agilewarsaw.com/events/98/"
    - name: "2016"
      url: "https://agilewarsaw.com/events/115/"
    - name: "2017"
      url: "https://agilewarsaw.com/events/130/"
    - name: "2018"
      url: "https://agilewarsaw.com/events/150/"
    - name: "2019"
      url: "https://agilewarsaw.com/events/179/"
    - name: "2020"
      url: "https://agilewarsaw.com/events/198/"
    - name: "2021"
      url: "https://agilewarsaw.com/events/228/"
    - name: "2022"
      url: "https://agilewarsaw.com/events/252/"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
     #text: "Free Registration"
     #link: "register"
     text: "Registration via Meetup"
     link: "https://www.meetup.com/agilewarsaw/events/291555202/"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
      #- name: "KMD"
      #logo: "img/logo_kmd.png"
      #url: "https://career.kmd.net/join-kmd-poland"
    
    - name: "BEC Poland"
      logo: "img/logo_bec.png"
      url: "https://www.linkedin.com/company/becpoland/"

    - name: "ProCognita"
      logo: "img/logo_procognita.png"
      url: "https://procognita.pl/"

    # - name: "mBank"
    #   logo: "img/logo-mbank-color.png"
    #   url: "https://mbank.pl/"

      #
      #  - name: "Vistula"
      #    logo: "img/logo_vistula.jpg"
      #    url: "http://www.vistula.edu.pl/"

      #- name: "Slido"
      #logo: "img/logo_slido.png"
      #url: "http://www.slido.com"

  # List of Partners
  Partners:
    - name: "Agile Warsaw"
      logo: "img/logo_AW.png"
      url: "http://agilewarsaw.com"

      # - name: "PKO BP"
      #   logo: "img/logo_PKOBP.jpg"
      #   url: "https://www.pkobp.pl"

      #- name: "PMI Oddział Warszawa"
      #logo: "img/logo_PMI.png"
      #url: "http://pmi.org.pl/pmi/oddzialy/warszawa/"

  # List of Media Partners
  Media:
      - name: "Agile Polska"
        logo: "img/logo_APL.png" 
        url: "http://agilepolska.pl/"

      - name: "Agile 247"
        logo: "img/logo_a247.jpg" 
        url: "http://www.agile247.pl/"

      - name: "Agile 4U"
        logo: "img/logo_agile4u.png" 
        url: "https://www.meetup.com/agile4u/"

      #- name: "Big Agile Theory"
      #logo: "img/logo_big-agile-theory.png" 
      #url: "https://www.meetup.com/Big-Agile-Theory/"
      
      - name: "LubLean"
        logo: "img/logo_LubLean.png" 
        url: "https://www.meetup.com/LubLean-and-Agile/"
      
      - name: "Agile Silesia"
        logo: "img/logo_agile-silesia.png" 
        url: "https://www.agilesilesia.pl/"
      
      # - name: "Agile Poznań"
      #   logo: "img/logo_ap_margines.png" 
      #   url: "https://agilepoznan.org/"

      # - name: "Fundacja Zwinność"
      #   logo: "img/logo_fundacja-zwinnosc.png" 
      #   url: "https://zwinnosc.org/"

      # - name: "ALE Kraków"
      #   logo: "img/logo-ale-krakow.png" 
      #   url: "https://www.alekrakow.com/"

      - name: "Kanban przy kawie"
        logo: "img/logo_kanban_przy_kawie.png" 
        url: "https://kanbanprzykawie.pl/"
        
      - name: "Agile Silesia"
        logo: "img/logo_AgileSilesia.png" 
        url: "https://www.agilesilesia.pl/"

      - name: "Agile Wrocław"
        logo: "img/logo-agile-wroclaw.png" 
        url: "https://www.meetup.com/pl-PL/agilewroclaw/"

  Orgs:
    - name: "Ewa Koprowska"
      img: "img/org_koprowska.png"
    - name: "Ania Przybyszewska"
      img: "img/org_przybyszewska.png"
    - name: "Piotr Radaj"
      img: "img/org_radaj.png"
    # - name: "Łukasz Przezorski"
    #   img: "img/org_przezorski.png"
    # - name: "Kinga Grabowska"
    #   img: "img/org_kinga.png"
    # - name: "Mateusz Srebrny"
    #   img: "img/org_srebrny.png"
    # - name: "Magdalena Walczak"
    #img: "img/org_walczak.png"
    - name: "Łukasz Szóstek"
      img: "img/org_szostek.png"
      #- name: "Piotr Szczygieł"
      #img: "img/org_szczygiel.png"

  # The entire schedule
  Schedule:
    - name: "Opening"
      time: "13h45"
      remark: "Please, be on time!<br>This is where you will be signing-up for workshops."

    - authors:
        - name: "Angel Diaz-Maroto"
          photo: "img/Angel-Diaz-Maroto.jpg"
          bio: "Certified Scrum Trainer (CST), Certified Enterprise Coach (CEC) & Certified Agile Leadership Educator (CALE) by the Scrum Alliance — Professional Certified Coach by the International Coach Federation with more than 15 years’ experience."
          #link:
            #href: ""
            #text: www
      presentation:
        title: "TBA"
        description: "Soon… <img class=\"icon-lang\" src=\"img/lang-gb.svg\">"

    - authors:
        - name: "Jaga Biernacka"
          #photo: "img/"
          #bio: ""
          #link:
            #href: ""
            #text: LinkedIn
      presentation:
        title: "TBA"
        description: "Niedługo… <img class=\"icon-lang\" src=\"img/lang-pl.svg\">"

    - authors:
        - name: "Adrian Janik"
          #photo: "img/"
          #bio: "Od 15 lat zajmuję się szkoleniem, rozwijaniem kompetencji miękkich.  Od 5 lat odkrywam świat zwinnych zespołów i przynoszę do niego narzędzia i rozwiązania wzmacniające zespołowość, samoorganizację oraz współodpowiedzialność.

Wspieram organizacje w planowaniu i skutecznym wdrażaniu zmian, dostarczam wiedzę i umiejętności związane z kompetencjami osobistymi, komunikacją oraz zespołowością. Pomagam liderom i członkom zespołów skutecznie pełnić ich role, a przez to budować samodzielne i odpowiedzialne teamy.

Jako trener i psycholog głęboko wierzę, że dobre relacje są nie tylko kluczem do sukcesu zespołów i organizacji, ale też źródłem dobrego i pełnego życia. Prywatnie podróżuję i biegam, a później odpoczywam z książką w ręku."
          #link:
            #href: ""
            #text: LinkedIn
      presentation:

        title: "TBA"
        description: "Niedługo… <img class=\"icon-lang\" src=\"img/lang-pl.svg\">"

    #- authors:
        #- name: "Łukasz Kosacki"
          #photo: "img/l-kosacki.jpg"
          #bio: "Łukasz is lifelong learner. Thanks to his teaching experience, he knows that active learning is the competence of the future. He has been involved with agile in its broadest sense since 2016. Co-organizer of Scrumvival, co-creator of several training courses for Scrum Masters. Supports the organization at every level helping organizations focus on the outcoms of the products they produce and more. He tries to be adaptive not to 'do adaptive' and to simplify our complex word."
          #link:
            #href: ""
            #text: LinkedIn
      #presentation:
        #title: "Let's Give Agile Back to Developers"
        #description: "Who needs agile? Will our products manage without agile?  Are our developers and our companies ready to take responsibility for agile?  Who started agile and why it was created? Why managers are comfortable with agile?  How to give responsibility for agile software development to development teams?  When we are more likely to make our product a product that matters, products that changes the world? <img class=\"icon-lang\" src=\"img/lang-gb.svg\">"
        description: "<img class=\"icon-lang\" src=\"img/lang-pl.svg\">"


    - name: "Parallel Workshops"
      #time: "14h15"
      remark: "The workshops will be held in parallel.<br>
      Workshop languages are mentioned in descriptions.<br><br>

      <strong>Jakub Bażela<br>
      Kanban Light</strong>
      <img class=\"icon-lang\" src=\"img/lang-gb.svg\"> <br>
      You will learn:<br>
      <ul style=\"padding-left: 0.5em;\">
<li>• How to map the flow of work?</li>
<li>• What makes a good Kanban board?</li>
<li>• What are rules of Kanban, if any?</li>
<li>• How are Kanban teams improving their services and ways of work?</li>
</ul>
      <br><br>

      <strong>Bogumiła Kwiatkowska-Koterba<br>
Współpraca popłaca - o efektywnej współpracy Scrum Mastera i Product Ownera</strong>
<img class=\"icon-lang\" src=\"img/lang-pl.svg\"><br>
W ramach warsztatu skupimy się na obszarze działania SM z PO.  
Porozmawiamy o dobrych praktykach we współpracy SM i PO oraz odpowiemy sobie na poniższe pytania: <br>
      <ul style=\"padding-left: 0.5em;\">
<li>• Jakie mogą być wzajemne oczekiwania między SM i PO?</li>
<li>• W czym SM realnie może pomóc PO i w jakim zakresie?</li>
<li>• W czym zazwyczaj PO widzi największą korzyść ze współpracy z SM?</li>
<li>• Jakie narzędzia w kontekście efektywności pracy może zaproponować SM - Product Ownerowi?</li>
<li>• Jak pracować z POs w zależności od ich poziomu zaawansowania w roli? </li>
<li>• Czego jako PO mogę oczekiwać od SM?</li>
<li>• Czego jako SM potrzebuje, aby osiągnąć satysfakcjonującą współpracę?</li>
</ul>
Rezultatem warsztatu będzie lista działań, praktyk i narzędzi, które Scrum Master i Product Owner mogą wykorzystać w codziennej pracy. <br>
Warsztat będzie idealny dla PO, którzy zastanawiają się w czym SM może ich na co dzień lepiej wspierać, dla SM, którzy zastanawiają się jak realnie wspierać POA oraz dla Managerów, którzy chcą pomagać zarówno SM jak i PO w efektywnej kooperacji.

<br><br>

     <strong>Noela Zdunek<br>
Scrum a wartości—w poszukiwaniu sensu</strong> <img class=\"icon-lang\" src=\"img/lang-pl.svg\"><br>

Jest to warsztat dość intymny–będziemy wszak rozmawiać o wartościach.
Po co zostały umieszczone w Scrum Guide i… dlaczego akurat te? Jak często rozmawiasz o nich z zespołem? Jak rozumiesz szacunek? Gdzie na co dzień towarzyszy Ci odwaga? Co nam daje skupienie, otwartość, zaangażowanie? Spróbujemy odpowiedzieć na trudne pytania, podzielimy się doświadczeniami, spostrzeżeniami i interpretacjami.
Rezultatem warsztatu będzie cel indywidualny oparty na wybranej wartości i–mam nadzieję–powracająca refleksja o tym, jakie miejsce wartości scrumowe zajmują w Twojej codziennej pracy.<br>
Warsztat przeznaczony dla Scrum Masterów na każdym etapie rozwoju.

<br><br>

     <strong>Krzysztof Niewiński<br>
Systems Thinking Basics</strong> <br>
TBA <img class=\"icon-lang\" src=\"img/lang-pl.svg\"><br>

      <br><br>

    <strong>Karolina Karbarz, Justyna Wykowska <br>
    TBA </strong> <img class=\"icon-lang\" src=\"img/lang-pl.svg\"><br>

      <br><br>

    "


      #- name: "Closing"
        #remark: ""

    - name: "Afterparty!"
      time: "~19:00"

    #- name: "Lunch"
      #remark: "You will have to take care of your own lunch. There are restauriants in the neighbourhood."



     ###########################
     ###  WORKSHOP TRAINERS  ###
     ###########################

    - authors:
        - name: "Jakub Bażela"
          photo: "img/bazela.jpg"
          bio: "Jakub Bażela is a Scrum Master, trainer, co-author of the book “How to tame Agile. A guide practically agile” (2018), a former consultant with scaling experience in banking industry, a happy husband, and a paw-rent of Burger the German Shepherd."
          #link:
              #href: ""
              #text: ""
      workshop: true
    
    - authors:
        - name: "Bogumiła Kwiatkowska-Koterba"
          photo: "img/kwiatkowska.jpg"
          bio: "Product Ownerka w Żabka Future (sercem cały czas Scrum Masterka :)<br>
Od 2 lat w roli Product Ownera, a od ponad roku zajmuje się kluczowym procesem w firmie tj. zamawianie towaru do sklepu. Na co dzień współpracuje z Franczyzobiorcami, biznesem i zespołem deweloperskim, konfrontując zbierane wymagania od różnych interesariuszy z danymi. Swoje wcześniejsze ponad 5 letnie doświadczenie jako Scrum Master / Agile Coach nadal wykorzystuje kiedy tylko ma do tego sposobność.
Nadal ciągnie ją do polepszania procesów, a poza tym uwielbia dzielić się wiedzą i polepszać efektywność w zespołach oraz organizacji.
Swój umysł odrywa od codzienności w tańcu towarzyskim ze swoim mężem.
A w wolnych chwilach uchwyca ludzkie emocje na fotografiach."
          link:
              href: "https://www.linkedin.com/in/kwiatkowskakoterba/"
              text: "LinkedIn"
      workshop: true
    
    - authors:
        - name: "Krzysztof Niewiński"
          photo: "img/Krzysztof_Niewinski_2022.png"
          bio: "Pracuję w branży IT od 2005 roku. Jestem inżynierem oprogramowania, trenerem, konsultantem i promotorem podejścia Agile i Lean. Od 15 lat podążam ścieżką „zwinności” i zajmowałem wiele stanowisk w procesie tworzenia oprogramowania — od programisty, przez analityka, managera, aż po Scrum Mastera / Agile Coacha. Od 7 lat jestem zawodowo zaangażowany w tworzenie adaptacyjnych, uczących się organizacji zorientowanych na klienta. Pracuję z dużymi grupami produktowymi. Jestem promotorem podejścia LeSS (Large Scale Scrum) w Polsce, umożliwiającego rozwój produktów na dużą skalę."
          link:
              #href: ""
              #text: ""
          # presentation: "title"
          # description: "desc"
      workshop: true


    - authors:
        - name: "Karolina Karbarz"
          photo: "img/Karolina_Karbarz_2022.jpeg"
          bio: "Projektuję od 2014 roku, w tym czasie z powodzeniem pracowałam nad produktami zarówno w dużej korporacji, jak i we współpracy z obiecującymi start-upami. Na co dzień zajmuję się badaniem potrzeb użytkowników, projektowaniem oraz walidacją tworzonych rozwiązań. Współtworzę jedną z najbardziej rozpoznawalnych na świecie konferencji o tworzeniu treści — soap!, która od ponad 8 lat przyciąga do Krakowa specjalistów z 35 krajów."
          link:
              #href: ""
              #text: ""
          # presentation: "title"
          # description: "desc"
        - name: "Justyna Wykowska"
          photo: "img/JWykowska_2022.png"
          bio: "Od 2005 roku nieustannie uczestniczę w rozwoju produktów.  Przez 11 lat pracowałam dla Motorola Solutions, prowadząc międzynarodowe zespoły opracowujące rozwiązania, w skład których wchodziło nie tylko oprogramowanie, ale również dedykowany sprzęt. Przebyłam drogę od członka zespołu, po managera kilkudziesięcioosobowego działu odpowiedzialnego za nowatorskie produkty i zbudowałam ponad 20 odnoszących sukcesy zespołów. Od 2014 roku wspieram firmy z różnych sektorów biznesu jako mentor i konsultant."
          link:
              #href: ""
              #text: ""
          # presentation: "title"
          # description: "desc"
      workshop: true

    - authors:
        - name: "Noela Zdunek"
          photo: "img/noela-zdunek.jpg"
          bio: "Scrum Masterką oficjalnie jest od dwóch lat, choć w oparciu o filary i wartości scrumowe działa intuicyjnie całe życie. Obecnie wspiera zwinną transformację w BNP Paribas na wszystkich szczeblach organizacji. Równie ważny jest dla niej deweloper, menedżer, jak i prezes zarządu – wierzy, że dzięki współpracy organizacje mogą osiągnąć najwięcej. Skupia się na budowaniu bezpiecznej atmosfery do pracy, eksperymentowania i ciągłego doskonalenia. Jako mentorka (m. in. w ScrumDzielni) działa na rzecz społeczności Agile i propagowania dobrych wzorców. Prywatnie – psia mama dwóch kundelków, fanka pizzy, piwa i playstation."
          link:
              href: "https://www.linkedin.com/in/noela-zdunek"
              text: "LinkedIn"
      workshop: true

    - authors:
        - name: "Łukasz Adamski"
          photo: "img/"
          bio: ""
          #link:
              #href: ""
              #text: ""
      workshop: true
    

    #####################
    ##     TEMPLATE    ##
    #####################
      # DWÓCH PRELEGENTÓW WYGLĄDA TAK:
      #    - authors:
      #        - name: "Hanna Kaczyńska"
      #          photo: "img/kaczynska.jpg"
      #          bio: "W PKO BP od 10 lat. Początki to obsługa klienta i sprzedaż, od 7 lat zajmuję się projektowaniem i prowadzeniem szkoleń w banku. Ponad rok temu zetknęłam się po raz pierwszy ze zwinnością, dziś sama nią zarażam jako Scrum Master i jako trener prowadzący szkolenia dla organizacji. Uwielbiam pracę z ludźmi i dla ludzi."
      #          link:
      #            href: "https://pl.linkedin.com/in/hanna-kaczyńska-508960142"
      #            text: "LinkedIn"
      #        - name: "Karol Krawiec"
      #          photo: "img/krawiec.jpg"
      #          bio: "Z sektorem bankowym związany od 15 lat, zaczynał swoje doświadczenie jako programista COBOL i konsultant w tworzeniu centralnego systemu bankowego. Kierował różnorodnymi projektami i programami IT dot. rozwoju produktów i usług bankowych, zarządzał zespołem Kierowników Projektów. Zainspirowany dążeniem ku zwinności, z pasją adaptuje podejście Agile – najpierw w zespołach IT, obecnie w ramach Transformacji Cyfrowej w skali całej Organizacji. Scrum Master, Product Owner i wyznawca idei ‘Da Się’."
      #          link:
      #            href: "https://pl.linkedin.com/in/karolkrawiec"
      #            text: "LinkedIn"
      #      presentation:
      #        title: "Dlaczego (czasem) warto zdjąć miarę u krawca?"
      #        description: "Rynek szkoleń pełen jest gotowych rozwiązań, które pozwalają zdobywać czy rozwijać potrzebne w organizacji kompetencje. Trudno jednak w komercyjnych propozycjach znaleźć zgrabny pakiet uszyty na miarę dla konkretnej firmy. Ustalone pół roku wcześniej z firmą szkoleniową programy szybko się dezaktualizują i nie zawsze elastycznie się negocjują. Kiedy do tego wszystkiego dodamy nowe w organizacji role: Product Owner i Scrum Master oraz założymy, że organizacja chce inwestować w ich rozwój - zapotrzebowanie ilościowe i jakościowe na różne szkolenia rośnie...
      #Jak firma może poradzić sobie z tym wyzwaniem? I dlaczego, zamiast kupować gotowe ubrania ze sklepowych wieszaków, czasem warto mieć firmowego krawca, który zawsze zdejmie z nas właściwą miarę?<br>Zapraszamy do wysłuchania opowieści o pewnej Akademii Zwinności…"

