publishDir: docs
baseurl: "https://abelight.agilewarsaw.com"
title: "ABE Light 2020"
canonifyurls: true
theme: "hugo-conference"

#GoogleAnalytics: "UA-112461830-1"

params:
  # Conference info
  Name: "ABE Light 2020"
  Description: "AgileByExample Light 2020"
  Date: "7 March (Saturday)"
  startDate: "2020-03-07T13:45"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Akademia Finansów i Biznesu VISTULA"
  Address: "Stokłosy 3"
  City:  "Warszawa"
  #State: "Quintana"
  Images: ["/img/ABElight-ikonka.png"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - partners
    - sponsors
    - media
    - orgs
    - previous
      #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About the conference"
    location: "Where?"
    speakers: "Who?"
    schedule: "Timetable"
    sponsors: "Sponsors"
    partners: "Partners"
    media: "Media Partners"
    orgs: "Organizers"
    contact: "Contact"
    previous: "Previous Editions"

  Previous:
    - name: "2018"
      url: "https://abelight-2018.agilewarsaw.com"
    - name: "2019"
      url: "https://abelight-2019.agilewarsaw.com"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
      text: "Free Registration"
      link: "register"
      #text: "Zarejestruj się gratis"
      #link: "register"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "ProCognita"
      logo: "img/logo_procognita.png"
      url: "https://procognita.pl/"

    - name: "Vistula"
      logo: "img/logo_vistula.jpg"
      url: "http://www.vistula.edu.pl/"

    - name: "Slido"
      logo: "img/logo_slido.png"
      url: "http://www.slido.com"

  # List of Partners
  Partners:
    - name: "Agile Warsaw"
      logo: "img/logo_AW.png"
      url: "http://agilewarsaw.com"

    - name: "PKO BP"
      logo: "img/logo_PKOBP.jpg"
      url: "https://www.pkobp.pl"

      #- name: "PMI Oddział Warszawa"
      #logo: "img/logo_PMI.png"
      #url: "http://pmi.org.pl/pmi/oddzialy/warszawa/"

  # List of Media Partners
  Media:
    - name: "Agile Polska"
      logo: "img/logo_APL.png" 
      url: "http://agilepolska.pl/"

    - name: "Agile 247"
      logo: "img/logo_a247.jpg" 
      url: "http://www.agile247.pl/"

  Orgs:
    - name: "Łukasz Szóstek"
      img: "img/org_szostek.png"
    - name: "Ania Przybyszewska"
      img: "img/org_przybyszewska.png"
    - name: "Mateusz Srebrny"
      img: "img/org_srebrny.png"
    - name: "Ewa Koprowska"
      img: "img/org_koprowska.png"
    - name: "Piotr Radaj"
      img: "img/org_radaj.png"
    - name: "Magdalena Walczak"
      img: "img/org_walczak.png"
    - name: "Łukasz Przezorski"
      img: "img/org_przezorski.png"
    #- name: "Michał Koprowski"
      #img: "img/org_koprowski.png"
      #- name: "Piotr Szczygieł"
      #img: "img/org_szczygiel.png"

  # The entire schedule
  Schedule:
    - name: "Start"
      time: "13h45"
      remark: "Please, be on time!"

    - authors:
        - name: "Gojko Adžić"
          photo: "img/Gojko.png"
          bio: "Gojko Adzic is a strategic software delivery consultant who works with ambitious teams to align software delivery with business goals and improve the quality of their software products and processes. Gojko specializes in are Agile and Lean quality improvement, in particular Impact Mapping, Agile Testing, Specification by Example and Behavior Driven Development.<br>
He is the winner of the 2016 European Software Testing Outstanding Achievement Award and the 2011 \"Most Influential Agile Testing Professional Award\"."
          link:
            href: "https://procognita.com/company/team/trainers/gojko-adzic/"
            text: www
      presentation:
        title: "Maximum Impact, Minimum Effort"
        description: "A big government IT project delivered two years ahead of schedule. A fraud detection initiative saving tens of millions more than predicted. An app that helped a city rebuild faster after a major disaster and save ten times more money than expected. Learn how early adopters use impact mapping to create big impacts and minimise effort, from large government departments to innovative consultancies and small startups.<br><br>
This talk is based on an extensive research with commercial organisations, government departments and non-profit agencies from all over the world. Gojko will present real-world case studies and distill their experience into useful tips that will enable you to speed up adoption, avoid common pitfalls and reach your goals faster."

    - name: "Workshops"
      remark: "There will be 6 parallel workshops.<br><br>
      
      <strong>1) Gojko Adzic: Given-when-then With Style</strong><br>
      Hands-on workshop where you will learn about the key techniques to make the most out of the Given-When-Then format for specifications and tests, and how to avoid the most common problems.<br>
      In English<br><br>
              
      <strong>2) Mariusz Petlic: Output vs. Outcome</strong><br>
      Do we generate value or costs? What's the benefit and what's not? We will check if we can distinguish it both at work and in private life.<br>
      In Polish<br><br>

      <strong>3) Tomasz Wykowski: Product Discovery</strong><br>
      What you don’t know about your product?<br>
      Join this session to learn why discovering the product is critical for its success and experience tools for defining Product Vision and Success Criteria.<br>
      In English unless all the participants speak Polish.<br><br>

      <strong>4) Justyna Wykowska: Backlog Prioritization Techniques</strong><br>
      When everything is important, nothing is important. During this workshop you’ll try different techniques for prioritizing your Product Backlog to find the ones that work for your company.<br>
      In English unless all the participants speak Polish<br><br>

      <strong>5) Ewa Koprowska, Dominik Jabłoński: Scrum Tale</strong><br>
      More info soon…<br><br>

      <strong>6) Klaudia Komacka: FAIL — First Attempt in Learning</strong><br>
      How to fail and learn during product development?<br>
      There is a practice that focuses on developing problem solving, scientific thinking and continuous improvement abilities. During this workshop, you will be encouraged to puzzle out the optimal solution through continuous experiments. We will discuss how to create a hypothesis, measure and validate it. In the end, we will celebrate the learning!<br><br>
      "

    - name: "Lunch"
      remark: "You will have to take care of your own lunch. There are restauriants in the neighbourhood."

    - authors:
        - name: "Zbigniew Sobiecki"
          photo: "img/ZbigniewS.jpg"
          bio: "I’ve been building software one way (with my own hands) or another (building teams and companies to do so) with dozens of technologies for almost 20 years now. Co-founded 5 companies.<br>
Currently at Arabella Labs, helping fantastic teams build products for exciting startups and world-famous corporations.<br>
In front of a computer (or terminal) screen since early ‘90s.<br>
Rookie marathon runner: so far managed to complete the original Marathon-Athens course in 2015 and not die immediately thereafter. "
          link:
              href: "http://zbigniew.me/"
              text: LinkedIn
      presentation:
        title: "Building New Products and Businesses vs. Cranking out Code"
        description: "Is it possible to successfully design and build new digital products and services from scratch with an external partner? If so, how does the process, the team, and the business arrangement differs from classic time & materials software house setup? Let's have a frank discussion about the common issues organizations face when trying to outsource product design and how to deal with them. Let's also get specific about focusing on outcomes instead of shipping new features. We will also touch on human and cultural aspects of the two approaches."

    - authors:
        - name: "Gosia Fiedorow"
          photo: "img/GFiedorow.jpg"
          bio: "Gosia Fiedorow, Industrial Designer turned Digital Product Designer, believes pixels and code are not that different from wood and carpentery. She’s leading the product design team at Codility, a software platform transforming the way enterprise companies hire, retain and grow engineering teams."
          link:
            href: "https://www.linkedin.com/in/gosiafiedorow/"
            text: LinkedIn
      presentation:
        title: "Finding Your Purpose in Chaos — a Designer’s Point of View"
        description: "In her talk, Gosia will share her story of how she has managed to fit the design mindset into software development; where work is never really done… and never ends up exactly how it was envisioned in the beginning."

    - authors:
        - name: "Aga Szóstek"
          photo: "img/Aga-120.jpg"
          bio: "Aga Szóstek, Ph.D. is a strategic designer. For the past two decades she worked at the forefront of combining design, technology and business. She collaborated with brands such as Google, Microsoft, Philips, Canon, Samsung, EY, Santander, ING, Orange and many more, bringing the experience-focused strategic approach to project teams and boardrooms. Her approach inspired many organisations to refocus and bet on experiences as their strategic differentiator.<br><br>
          Next to consulting, Aga designs <a href=\"http://seed-cards.com\" target=\"blank\">tools</a> aiming to support delivering unique experiences and co-hosts a podcast about creative leadership: <a href=\"http://catchingthenextwavepodcast.com\" target=\"blank\">Catching The Next Wave</a>. She graduated with her Ph.D. from the Eindhoven University of Technology, The Netherlands, and teaches experience design all around the world from the alternative business school Kaospilot in Denmark to Canterbury University in Christchurch, New Zealand."
          link:
            href: "https://pl.linkedin.com/in/agnieszka-sz%C3%B3stek-5aa2321"
            text: "LinkedIn"
      presentation:
        title: "It's All About the Axperience"
        description: "We talk about how to design the right products in the right way, right? But is it truly the thing we should focus on? In my presentation, I will do my best to convince you that, in fact, we should focus on defining what sort of experience we aim at before we focus on designing products and services."


    - name: "Afterparty"
      remark: "Close by…"
      time: "~19h30"


     ###########################
     ###  WORKSHOP TRAINERS  ###
     ###########################

    - authors:
        - name: "Tomasz Wykowski"
          photo: "img/TomekWykowski.png"
          bio: "“We learn thru all our life, therefore learning needs to be fun.”<br>
          As an Agile Coach and Trainer, Tomasz supports individuals and organizations in their quest for Agility, better results and amazing workplace. He's the first Polish Certified Scrum Trainer and LeSS-Friendly Scrum Trainer. He understands the needs of young companies and helps them succeed in their markets.<br>
Tomasz holds a Master's Degree in Automatic and Robotic and has a broad experience in software development from different perspectives, including engineering, quality assurance, project management and Agile Coaching. In 2010 he founded ProCognita, a training and consulting company."
          link:
              href: "https://procognita.com/company/team/trainers/tomasz-wykowski/"
              text: "www"
      workshop: true

    - authors:
        - name: "Justyna Wykowska"
          photo: "img/JustynaWykowska.png"
          bio: "“Behind every product, there are people who are creating it.”<br>
An engineer, software developer, manager, Product Owner, Scrum Master, trainer, personal coach, and Agile specialist. By combining a technical degree with soft skills education and real-life experience, Justyna emphasizes the collaboration and communication factors in organizations and teams' dynamics.<br>
For almost a decade Justyna has led diverse multinational and distributed teams involved in huge projects. Since 2014 she is working with ProCognita as an Agile Coach and Trainer, supporting companies from many business sectors including customer support, software and hardware development."
          link:
              href: "https://procognita.com/company/team/trainers/justyna-wykowska/"
              text: "www"
      workshop: true

    - authors:
        - name: "Mariusz Petlic"
          photo: "img/MariuszPetlic.png"
          bio: "“The quality of the product is created by the quality of the process.”<br>
          I am fascinated by the quality of the product and the process. I would like to help you refine your product so that customers are satisfied and recommend it to others. That is why it is important to constantly improve the process of creating a product. If you do not want to spend money on activities that may end in failure, we can find together the best models for creating new products and developing existing ones.<br>
I worked with companies: ComputerLand, Systemy Kodów Kreskowych, Hurra.com, eSky.pl. As an active Scrum Master, I supported and built teams. Now I'm an Agile Coach. At work with major companies I have learned how to test products and I will gladly share this knowledge with you."
          link:
              href: "https://procognita.com/company/team/trainers/mariusz-petlic/"
              text: "www"
      workshop: true

      #- authors:
      #- name: "Ewa Koprowska"
      #photo: "img/.jpg"
      #bio: ""
      #link:
      #href: ""
      #text: "www"
      #workshop: true

    - authors:
        - name: "Domink Jabłoński"
          photo: "img/DominikJ.jpg"
          bio: "Agile Consultant at <a href=\"https://codesprinters.pl/\">Code Sprinters</a> with a diverse experience ranging from sales, through customer service, to QA and scrum mastery. He gained experience in small software houses as well as in HR and banking corporations. Apart from his fascination with Agile methodologies and how they change our work and life, he is an avid board game geek."
          link:
             href: "https://www.linkedin.com/in/dominik-jab%C5%82onski-7baa9265/"
             text: "LinkedIn"
      workshop: true

    - authors:
        - name: "Klaudia Komacka"
          photo: "img/KlaudiaK.jpg"
          bio: "Agile and Lean Catalyst / Design Thinking Facilitator. She is a people person helping individuals to become a great team. Supports understanding of Agile and Lean with a focus on the Human. Design Thinking and Management 3.0 enthusiast. She co-organises the <a href=\"http://accpl.pl/\">Agile Coach Camp conference</a> in Poland."
          link:
              href: "https://www.linkedin.com/in/klaudiakomacka/"
              text: "LinkedIn"
      workshop: true
  

      # DWÓCH PRELEGENTÓW WYGLĄDA TAK:
      #    - authors:
      #        - name: "Hanna Kaczyńska"
      #          photo: "img/kaczynska.jpg"
      #          bio: "W PKO BP od 10 lat. Początki to obsługa klienta i sprzedaż, od 7 lat zajmuję się projektowaniem i prowadzeniem szkoleń w banku. Ponad rok temu zetknęłam się po raz pierwszy ze zwinnością, dziś sama nią zarażam jako Scrum Master i jako trener prowadzący szkolenia dla organizacji. Uwielbiam pracę z ludźmi i dla ludzi."
      #          link:
      #            href: "https://pl.linkedin.com/in/hanna-kaczyńska-508960142"
      #            text: "LinkedIn"
      #        - name: "Karol Krawiec"
      #          photo: "img/krawiec.jpg"
      #          bio: "Z sektorem bankowym związany od 15 lat, zaczynał swoje doświadczenie jako programista COBOL i konsultant w tworzeniu centralnego systemu bankowego. Kierował różnorodnymi projektami i programami IT dot. rozwoju produktów i usług bankowych, zarządzał zespołem Kierowników Projektów. Zainspirowany dążeniem ku zwinności, z pasją adaptuje podejście Agile – najpierw w zespołach IT, obecnie w ramach Transformacji Cyfrowej w skali całej Organizacji. Scrum Master, Product Owner i wyznawca idei ‘Da Się’."
      #          link:
      #            href: "https://pl.linkedin.com/in/karolkrawiec"
      #            text: "LinkedIn"
      #      presentation:
      #        title: "Dlaczego (czasem) warto zdjąć miarę u krawca?"
      #        description: "Rynek szkoleń pełen jest gotowych rozwiązań, które pozwalają zdobywać czy rozwijać potrzebne w organizacji kompetencje. Trudno jednak w komercyjnych propozycjach znaleźć zgrabny pakiet uszyty na miarę dla konkretnej firmy. Ustalone pół roku wcześniej z firmą szkoleniową programy szybko się dezaktualizują i nie zawsze elastycznie się negocjują. Kiedy do tego wszystkiego dodamy nowe w organizacji role: Product Owner i Scrum Master oraz założymy, że organizacja chce inwestować w ich rozwój - zapotrzebowanie ilościowe i jakościowe na różne szkolenia rośnie...
      #Jak firma może poradzić sobie z tym wyzwaniem? I dlaczego, zamiast kupować gotowe ubrania ze sklepowych wieszaków, czasem warto mieć firmowego krawca, który zawsze zdejmie z nas właściwą miarę?<br>Zapraszamy do wysłuchania opowieści o pewnej Akademii Zwinności…"

