publishDir: docs
#baseurl: "https://abelight.agilewarsaw.com"
baseurl: "https://abelight.netlify.com"
title: "ABE Light 2019"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-112461830-1"

params:
  # Conference info
  Name: "ABE Light 2019"
  Description: "AgileByExample Light 2019"
  Date: "30 March (Saturday)"
  startDate: "2018-03-30T13:45"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Akademia Finansów i Biznesu VISTULA"
  Address: "Stokłosy 3"
  City:  "Warszawa"
  #State: "Quintana"
  Images: ["/img/ABElight-ikonka.png"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - partners
    - media
    - orgs
      #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About the conference"
    location: "Where?"
    speakers: "Who?"
    schedule: "Timetable"
    sponsors: "Sponsors"
    partners: "Partners"
    media: "Media Partners"
    orgs: "Organizers"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
      text: "Registration is closed"
      #link: "register"
      #text: "Zarejestruj się gratis"
      #link: "register"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "ProCognita"
      logo: "img/logo_procognita.png"
      url: "https://procognita.pl/"

    - name: "Vistula"
      logo: "img/logo_vistula.jpg"
      url: "http://www.vistula.edu.pl/"

    - name: "Slido"
      logo: "img/logo_slido.jpg"
      url: "http://www.slido.com"

  # List of Partners
  Partners:
    - name: "Agile Warsaw"
      logo: "img/logo_AW.png"
      url: "http://agilewarsaw.com"

    - name: "Deloitte"
      logo: "img/logo-deloitte-white.png"
      url: "https://www2.deloitte.com/pl/pl.html"

      #- name: "PMI Oddział Warszawa"
      #logo: "img/logo_PMI.png"
      #url: "http://pmi.org.pl/pmi/oddzialy/warszawa/"

  # List of Media Partners
  Media:
    - name: "Agile Polska"
      logo: "img/logo_APL.png" 
      url: "http://agilepolska.pl/"

    - name: "Agile 247"
      logo: "img/logo_a247.png" 
      url: "http://www.agile247.pl/"

  Orgs:
    - name: "Ewa Koprowska"
      img: "img/org_koprowska.png"
    - name: "Piotr Radaj"
      img: "img/org_radaj.png"
    - name: "Mateusz Srebrny"
      img: "img/org_srebrny.png"
    - name: "Łukasz Szóstek"
      img: "img/org_szostek.png"
    - name: "Magdalena Walczak"
      img: "img/org_walczak.png"
    #- name: "Michał Koprowski"
      #img: "img/org_koprowski.png"
      #- name: "Piotr Szczygieł"
      #img: "img/org_szczygiel.png"

  # The entire schedule
  Schedule:
    - name: "Start"
      time: "13h45"
      remark: "Please, be on time!"

    #- name: "AZA Group"
      #time: "13h45"
      #remark: "Kilka słów od sponsora: ,,Młodzi i ambitni. Jak bardzo zwinni? Czyli agile w AZAGroup''."


    - authors:
        - name: "Jurgen De Smet"
          photo: "img/jurgenDeSmet.jpg"
          bio: "I am a Certified LeSS (Large-Scale Scrum) Trainer, Licensed Management 3.0 Trainer and ambassador at Startups.be, the group spearheading the entrepreneurial environment in Belgium. Inside I am still skateboarding, picking up new moves, adapting to ever-changing environments and freestyling with the best, wherever fresh design concepts for improving the world of work are emerging and being perfected."
          #company: "Linux Foundation"
          link:
            href: "https://procognita.com/company/team/trainers/jurgen-de-smet/"
            text: "www"
      presentation:
        title: "Why Should Most Organisations Ditch Scrum!"
        description: "Thanks to HBR, McKinsey and more of those, Agile has become mainstream but is it Agile? I see Agile being used as synonym of Scrum even though Agile is more of an umbrella where Scrum is just one flavour of getting there. Many inquiries show that Scrum is the most used Agile flavour in the world and I’m here to tell you to stop that movement unless you truly mean it. Let me guide you through some basic elements and help you evaluate if you and your organisation should ditch Scrum or not. Help you recognise if you are truly a Scrum Master or rather a Scrum Novice. And much more."

    - authors:
        - name: "ProCognita"
          photo: "img/logo_procognita.png"
          bio: "We believe that there will always be better ways to create products and services.<br>We are happy to help those who want to discover them with us.<br>We promote the Agile and Lean approach to product development. We share knowledge and support organizations through training, mentoring, talks and workshops. Our partners provide us with support and knowledge, and a different perspective to work with customers."
          link:
            href: "https://procognita.pl/"
            text: "www"
      presentation:
        title: "Agile Workshops"
        description: "There will be 5 parallel workshops.<br>
        <strong>1) LeSS roleplay</strong><br>
        Big organization, the complex product with multiple stakeholders, couple teams collaborating together. Try LeSS challenge in a safe environment. Join a roleplaying game with the most typical challenges faced by big companies.<br>
        &nbsp Led by Justyna Wykowska<br>
        &nbsp Language: English / Polish<br><br>

        <strong>2) Responsibilities in Scrum</strong><br>
        There is plenty of duties, and responsible decisions to take during delivering the product. In Scrum, we have three roles that must deal with all of this.<br>
        How to correctly distribute responsibility and deal with assigned tasks? How is it in your and other organizations? We invite you to the discussion supported by tool Management in Scrum.<br>
        In addition, you will have the opportunity to get to know and test an interesting approach to facilitating the meeting.<br>
        &nbsp Led by Mariusz Petlic, Radek Gamracy<br>
        &nbsp Language: English / Polish<br><br>
        
        <strong>3) Cynefin Lego workshop</strong><br>
        There’s no one-size-fits-all approach to problem-solving, as the right decision-making model depends on the domain you’re in. The Cynefin model, created by Dave Snowden, explains how to make decisions in different domains, and this game will let you experience obvious, complicated, complex and chaotic systems.<br>
        After this session, you will be able to explain why different domains need different decision-making models, identify the domain you’re currently in and choose the right approach to solve your problem.<br>
        &nbsp Led by Tomasz Wykowski<br>
        &nbsp language: English / Polish<br><br>
        
        <strong>4) Vision, Strategy, and Tactics</strong><br>
        In other words, how to turn an idea into a valuable product. How and what strategic and tactical tools can we use to maximize the value of the product?<br>
        During the workshop, we will learn the basic tools for product development management, ie. Elevator pitch (visioning & strategy), Impact Map (roadmap), and Product Backlog (tactics).<br>
        &nbsp Led by Krzysztof Niewiński<br>
        &nbsp Language: English / Polish<br><br>

        <strong>5) Systems Modelling for Organisational Design</strong><br>
        Many organisations are adopting Agile practices, mnay organisations are finding ways to improve but little of them are truly designing their organisations with understanding. Blindly adopting any kind of Agile Scaling framework will result in tensions that require effort and energy that could be used to deliver outcome instead.<br>
        Want to avoid this in the future?<br>
        Want to get a better understanding?<br>
        Want to acquire a tool to help your organisation?<br>
        We will guide you through a series of exercises that will generate insights in the organisational dynamics that are in place within a R&D organisation and it's surrounding departments. With that insight you will be able to design a perfect organisation and evaluate existing Agile Scaling frameworks on best fit in order to avoid tensions and maximise impact.<br>
        &nbsp Led by Jurgen de Smet<br>
        &nbsp Language: English
"

    - name: "Lunch"
      remark: "You will have to take care of your own lunch. The Vistula canteen will be forewarned about our event so they will be ready for you if you choose to eat there."

    - authors:
        - name: "Agnieszka Balcer-Thinlay"
          photo: "img/AgaBT.jpg"
          bio: "Agnieszka is a Director of Product Research at Codility, working with both qualitative as well as quantitative data and advocating for insights-driven decision making. She has been collecting research experience for over 14 years, working for variety of categories - software, FMCG, cosmetics, automotive, household goods, services and telecommunications (including running Marketing Research Team at Play for over 6 years). She also  teaches courses on research and ethnography to post-graduate students at Warsaw School of Economics, Kozminski Academy and Warsaw School of Social Psychology."
          link:
            href: "https://www.linkedin.com/in/agnieszka-balcer-thinlay-83934345"
            text: LinkedIn
      presentation:
        title: "Filtering out bad ideas: how we decide what not to do @Codility"
        description: "A lot is being written on how to select features for further development: how to sieve through the ideas, agree on the most promising ones and deliver them ASAP. Not only because you get to select the optimal projects - but also (what is sometimes forgotten) avoid doing things that might drive your developer team far away from where they should be spending their time and effort. Saving resources (time of developers) for the right ideas is just as important as selecting the right ideas in the first place. I would like to show an example of 2 features we have terminated at Codility just before the development phase thanks to research and internal cooperation, saving the company months of work on a feature that might not be the most valuable one at the time. Research methods used: qualitative concept tests (also known in Codility as Pizza Disaster Tests) and quantitative analysis of internal data. Important ingredients of the success: strong Research – Product Manager cooperation, feedback ownership and clear assumptions behind the development (we know what problem it was going to solve)."

    - authors:
        - name: "Paweł Polewicz"
          photo: "img/reef.jpg"
          bio: "Pawel is a software engineer with 16 years of professional experience ranging from programming in a local startup to leading large teams for an international corporation. Initially focused on doing things right, later switched to doing the right things. Three years ago he resigned from a full time position and started a software house and completed over 60 projects for businesses of all sizes based in USA, Canada, UK and Australia, from toilet paper level tracker to fintech timeseries analyzers."
          link:
            href: "http://reef.pl"
            text: "www"
      presentation:
        title: "Death as BFF of every project"
        description: "We've all heard interesting stories about projects which almost died, but have miraculously recovered. We can learn a lot from them by focusing on the turning points. In this talk we are going to go through a few examples and see how technological and organizational barriers can suddenly be eliminated in presence of a key catalyst: Fear Of Death. ☠️☠️☠️"

    - authors:
        - name: "Hanna Kaczyńska"
          photo: "img/kaczynska.jpg"
          bio: "W PKO BP od 10 lat. Początki to obsługa klienta i sprzedaż, od 7 lat zajmuję się projektowaniem i prowadzeniem szkoleń w banku. Ponad rok temu zetknęłam się po raz pierwszy ze zwinnością, dziś sama nią zarażam jako Scrum Master i jako trener prowadzący szkolenia dla organizacji. Uwielbiam pracę z ludźmi i dla ludzi."
          link:
            href: "https://pl.linkedin.com/in/hanna-kaczyńska-508960142"
            text: "LinkedIn"
        - name: "Karol Krawiec"
          photo: "img/krawiec.jpg"
          bio: "Z sektorem bankowym związany od 15 lat, zaczynał swoje doświadczenie jako programista COBOL i konsultant w tworzeniu centralnego systemu bankowego. Kierował różnorodnymi projektami i programami IT dot. rozwoju produktów i usług bankowych, zarządzał zespołem Kierowników Projektów. Zainspirowany dążeniem ku zwinności, z pasją adaptuje podejście Agile – najpierw w zespołach IT, obecnie w ramach Transformacji Cyfrowej w skali całej Organizacji. Scrum Master, Product Owner i wyznawca idei ‘Da Się’."
          link:
            href: "https://pl.linkedin.com/in/karolkrawiec"
            text: "LinkedIn"
      presentation:
        title: "Dlaczego (czasem) warto zdjąć miarę u krawca?"
        description: "Rynek szkoleń pełen jest gotowych rozwiązań, które pozwalają zdobywać czy rozwijać potrzebne w organizacji kompetencje. Trudno jednak w komercyjnych propozycjach znaleźć zgrabny pakiet uszyty na miarę dla konkretnej firmy. Ustalone pół roku wcześniej z firmą szkoleniową programy szybko się dezaktualizują i nie zawsze elastycznie się negocjują. Kiedy do tego wszystkiego dodamy nowe w organizacji role: Product Owner i Scrum Master oraz założymy, że organizacja chce inwestować w ich rozwój - zapotrzebowanie ilościowe i jakościowe na różne szkolenia rośnie...
Jak firma może poradzić sobie z tym wyzwaniem? I dlaczego, zamiast kupować gotowe ubrania ze sklepowych wieszaków, czasem warto mieć firmowego krawca, który zawsze zdejmie z nas właściwą miarę?<br>Zapraszamy do wysłuchania opowieści o pewnej Akademii Zwinności…"

    - name: "Afterparty"
      remark: "Close by…"
      time: "~19h30"


      #    - name: "Steve Wozniak"
      #      photo: "/img/speaker.jpg"
      #      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      #      company: "Apple, Inc."
      #      link:
      #        href: "http://twitter.com/woz"
      #        text: "@woz"
      #      presentation:
      #        title: "Why do I prefer Android over iPhone"
      #        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      #        time: "17h00"
